-- 1) COMPANY
CREATE TABLE IF NOT EXISTS COMPANY (
  COMPANY_ID SERIAL PRIMARY KEY,
  COMPANY_NAME TEXT NOT NULL,
  LEGAL_NAME TEXT,
  TAX_NUMBER TEXT,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  DELETED_AT TIMESTAMPTZ
);
-- 2) BRANCH
CREATE TABLE IF NOT EXISTS BRANCH (
  BRANCH_ID SERIAL PRIMARY KEY,
  COMPANY_ID INTEGER NOT NULL REFERENCES COMPANY (COMPANY_ID),
  BRANCH_NAME TEXT NOT NULL,
  BRANCH_CODE TEXT UNIQUE,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  DELETED_AT TIMESTAMPTZ
);
-- 3) ROLE
CREATE TABLE IF NOT EXISTS ROLE (
  ROLE_ID SERIAL PRIMARY KEY,
  ROLE_CODE TEXT NOT NULL UNIQUE,
  -- e.g. 'ADMIN', 'USER'
  ROLE_NAME TEXT NOT NULL,
  -- e.g. 'Administrator', 'Standard User'
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- 4) APP_USER
CREATE TABLE IF NOT EXISTS APP_USER (
  USER_ID SERIAL PRIMARY KEY,
  COMPANY_ID INTEGER NOT NULL REFERENCES COMPANY (COMPANY_ID),
  BRANCH_ID INTEGER REFERENCES BRANCH (BRANCH_ID),
  ROLE_ID INTEGER NOT NULL REFERENCES ROLE (ROLE_ID),
  USERNAME TEXT NOT NULL UNIQUE,
  EMAIL TEXT NOT NULL UNIQUE,
  PASSWORD_HASH TEXT NOT NULL,
  FULL_NAME TEXT NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  DELETED_AT TIMESTAMPTZ
);
-- 5) CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER (
  CUSTOMER_ID SERIAL PRIMARY KEY,
  COMPANY_ID INTEGER NOT NULL REFERENCES COMPANY (COMPANY_ID),
  BRANCH_ID INTEGER REFERENCES BRANCH (BRANCH_ID),
  CUSTOMER_NAME TEXT NOT NULL,
  PHONE TEXT,
  EMAIL TEXT,
  ADDRESS TEXT,
  TAX_NUMBER TEXT,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CREATED_BY_USER_ID INTEGER,
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  DELETED_AT TIMESTAMPTZ
);
-- 6) TAX
CREATE TABLE IF NOT EXISTS TAX (
  TAX_ID SERIAL PRIMARY KEY,
  COMPANY_ID INTEGER NOT NULL REFERENCES COMPANY (COMPANY_ID),
  TAX_NAME TEXT NOT NULL,
  -- e.g. 'Standard VAT 15%'
  TAX_RATE NUMERIC(5, 4) NOT NULL,
  -- e.g. 0.1500 for 15%
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- 7) INVENTORY_ITEM
CREATE TABLE IF NOT EXISTS INVENTORY_ITEM (
  INVENTORY_ITEM_ID SERIAL PRIMARY KEY,
  COMPANY_ID INTEGER NOT NULL REFERENCES COMPANY (COMPANY_ID),
  BRANCH_ID INTEGER REFERENCES BRANCH (BRANCH_ID),
  SKU TEXT NOT NULL UNIQUE,
  ITEM_NAME TEXT NOT NULL,
  DESCRIPTION TEXT,
  UNIT_PRICE NUMERIC(12, 4) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CREATED_BY_USER_ID INTEGER,
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  DELETED_AT TIMESTAMPTZ
);